//
// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha3 "github.com/kdubbo/client-go/pkg/apis/networking/v1alpha3"
	networkingv1alpha3 "github.com/kdubbo/client-go/pkg/applyconfiguration/networking/v1alpha3"
	typednetworkingv1alpha3 "github.com/kdubbo/client-go/pkg/clientset/versioned/typed/networking/v1alpha3"
	gentype "k8s.io/client-go/gentype"
)

// fakeWorkloadEntries implements WorkloadEntryInterface
type fakeWorkloadEntries struct {
	*gentype.FakeClientWithListAndApply[*v1alpha3.WorkloadEntry, *v1alpha3.WorkloadEntryList, *networkingv1alpha3.WorkloadEntryApplyConfiguration]
	Fake *FakeNetworkingV1alpha3
}

func newFakeWorkloadEntries(fake *FakeNetworkingV1alpha3, namespace string) typednetworkingv1alpha3.WorkloadEntryInterface {
	return &fakeWorkloadEntries{
		gentype.NewFakeClientWithListAndApply[*v1alpha3.WorkloadEntry, *v1alpha3.WorkloadEntryList, *networkingv1alpha3.WorkloadEntryApplyConfiguration](
			fake.Fake,
			namespace,
			v1alpha3.SchemeGroupVersion.WithResource("workloadentries"),
			v1alpha3.SchemeGroupVersion.WithKind("WorkloadEntry"),
			func() *v1alpha3.WorkloadEntry { return &v1alpha3.WorkloadEntry{} },
			func() *v1alpha3.WorkloadEntryList { return &v1alpha3.WorkloadEntryList{} },
			func(dst, src *v1alpha3.WorkloadEntryList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha3.WorkloadEntryList) []*v1alpha3.WorkloadEntry {
				return list.Items
			},
			func(list *v1alpha3.WorkloadEntryList, items []*v1alpha3.WorkloadEntry) {
				list.Items = items
			},
		),
		fake,
	}
}
