//
// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha3 "github.com/kdubbo/client-go/pkg/clientset/versioned/typed/networking/v1alpha3"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeNetworkingV1alpha3 struct {
	*testing.Fake
}

func (c *FakeNetworkingV1alpha3) CircuitBreakerPolicies(namespace string) v1alpha3.CircuitBreakerPolicyInterface {
	return newFakeCircuitBreakerPolicies(c, namespace)
}

func (c *FakeNetworkingV1alpha3) DxgateServices(namespace string) v1alpha3.DxgateServiceInterface {
	return newFakeDxgateServices(c, namespace)
}

func (c *FakeNetworkingV1alpha3) FaultInjectionPolicies(namespace string) v1alpha3.FaultInjectionPolicyInterface {
	return newFakeFaultInjectionPolicies(c, namespace)
}

func (c *FakeNetworkingV1alpha3) ServiceActivationPolicies(namespace string) v1alpha3.ServiceActivationPolicyInterface {
	return newFakeServiceActivationPolicies(c, namespace)
}

func (c *FakeNetworkingV1alpha3) ServiceEntries(namespace string) v1alpha3.ServiceEntryInterface {
	return newFakeServiceEntries(c, namespace)
}

func (c *FakeNetworkingV1alpha3) WorkloadEntries(namespace string) v1alpha3.WorkloadEntryInterface {
	return newFakeWorkloadEntries(c, namespace)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeNetworkingV1alpha3) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
