//
// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha3 "github.com/kdubbo/client-go/pkg/apis/security/v1alpha3"
	securityv1alpha3 "github.com/kdubbo/client-go/pkg/applyconfiguration/security/v1alpha3"
	typedsecurityv1alpha3 "github.com/kdubbo/client-go/pkg/clientset/versioned/typed/security/v1alpha3"
	gentype "k8s.io/client-go/gentype"
)

// fakeRequestAuthentications implements RequestAuthenticationInterface
type fakeRequestAuthentications struct {
	*gentype.FakeClientWithListAndApply[*v1alpha3.RequestAuthentication, *v1alpha3.RequestAuthenticationList, *securityv1alpha3.RequestAuthenticationApplyConfiguration]
	Fake *FakeSecurityV1alpha3
}

func newFakeRequestAuthentications(fake *FakeSecurityV1alpha3, namespace string) typedsecurityv1alpha3.RequestAuthenticationInterface {
	return &fakeRequestAuthentications{
		gentype.NewFakeClientWithListAndApply[*v1alpha3.RequestAuthentication, *v1alpha3.RequestAuthenticationList, *securityv1alpha3.RequestAuthenticationApplyConfiguration](
			fake.Fake,
			namespace,
			v1alpha3.SchemeGroupVersion.WithResource("requestauthentications"),
			v1alpha3.SchemeGroupVersion.WithKind("RequestAuthentication"),
			func() *v1alpha3.RequestAuthentication { return &v1alpha3.RequestAuthentication{} },
			func() *v1alpha3.RequestAuthenticationList { return &v1alpha3.RequestAuthenticationList{} },
			func(dst, src *v1alpha3.RequestAuthenticationList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha3.RequestAuthenticationList) []*v1alpha3.RequestAuthentication {
				return list.Items
			},
			func(list *v1alpha3.RequestAuthenticationList, items []*v1alpha3.RequestAuthentication) {
				list.Items = items
			},
		),
		fake,
	}
}
