//
// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha3 "github.com/kdubbo/client-go/pkg/apis/security/v1alpha3"
	securityv1alpha3 "github.com/kdubbo/client-go/pkg/applyconfiguration/security/v1alpha3"
	typedsecurityv1alpha3 "github.com/kdubbo/client-go/pkg/clientset/versioned/typed/security/v1alpha3"
	gentype "k8s.io/client-go/gentype"
)

// fakeAuthorizationPolicies implements AuthorizationPolicyInterface
type fakeAuthorizationPolicies struct {
	*gentype.FakeClientWithListAndApply[*v1alpha3.AuthorizationPolicy, *v1alpha3.AuthorizationPolicyList, *securityv1alpha3.AuthorizationPolicyApplyConfiguration]
	Fake *FakeSecurityV1alpha3
}

func newFakeAuthorizationPolicies(fake *FakeSecurityV1alpha3, namespace string) typedsecurityv1alpha3.AuthorizationPolicyInterface {
	return &fakeAuthorizationPolicies{
		gentype.NewFakeClientWithListAndApply[*v1alpha3.AuthorizationPolicy, *v1alpha3.AuthorizationPolicyList, *securityv1alpha3.AuthorizationPolicyApplyConfiguration](
			fake.Fake,
			namespace,
			v1alpha3.SchemeGroupVersion.WithResource("authorizationpolicies"),
			v1alpha3.SchemeGroupVersion.WithKind("AuthorizationPolicy"),
			func() *v1alpha3.AuthorizationPolicy { return &v1alpha3.AuthorizationPolicy{} },
			func() *v1alpha3.AuthorizationPolicyList { return &v1alpha3.AuthorizationPolicyList{} },
			func(dst, src *v1alpha3.AuthorizationPolicyList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha3.AuthorizationPolicyList) []*v1alpha3.AuthorizationPolicy {
				return list.Items
			},
			func(list *v1alpha3.AuthorizationPolicyList, items []*v1alpha3.AuthorizationPolicy) {
				list.Items = items
			},
		),
		fake,
	}
}
