//
// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha3

import (
	context "context"

	networkingv1alpha3 "github.com/kdubbo/client-go/pkg/apis/networking/v1alpha3"
	applyconfigurationnetworkingv1alpha3 "github.com/kdubbo/client-go/pkg/applyconfiguration/networking/v1alpha3"
	scheme "github.com/kdubbo/client-go/pkg/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ServiceActivationPoliciesGetter has a method to return a ServiceActivationPolicyInterface.
// A group's client should implement this interface.
type ServiceActivationPoliciesGetter interface {
	ServiceActivationPolicies(namespace string) ServiceActivationPolicyInterface
}

// ServiceActivationPolicyInterface has methods to work with ServiceActivationPolicy resources.
type ServiceActivationPolicyInterface interface {
	Create(ctx context.Context, serviceActivationPolicy *networkingv1alpha3.ServiceActivationPolicy, opts v1.CreateOptions) (*networkingv1alpha3.ServiceActivationPolicy, error)
	Update(ctx context.Context, serviceActivationPolicy *networkingv1alpha3.ServiceActivationPolicy, opts v1.UpdateOptions) (*networkingv1alpha3.ServiceActivationPolicy, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, serviceActivationPolicy *networkingv1alpha3.ServiceActivationPolicy, opts v1.UpdateOptions) (*networkingv1alpha3.ServiceActivationPolicy, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*networkingv1alpha3.ServiceActivationPolicy, error)
	List(ctx context.Context, opts v1.ListOptions) (*networkingv1alpha3.ServiceActivationPolicyList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *networkingv1alpha3.ServiceActivationPolicy, err error)
	Apply(ctx context.Context, serviceActivationPolicy *applyconfigurationnetworkingv1alpha3.ServiceActivationPolicyApplyConfiguration, opts v1.ApplyOptions) (result *networkingv1alpha3.ServiceActivationPolicy, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, serviceActivationPolicy *applyconfigurationnetworkingv1alpha3.ServiceActivationPolicyApplyConfiguration, opts v1.ApplyOptions) (result *networkingv1alpha3.ServiceActivationPolicy, err error)
	ServiceActivationPolicyExpansion
}

// serviceActivationPolicies implements ServiceActivationPolicyInterface
type serviceActivationPolicies struct {
	*gentype.ClientWithListAndApply[*networkingv1alpha3.ServiceActivationPolicy, *networkingv1alpha3.ServiceActivationPolicyList, *applyconfigurationnetworkingv1alpha3.ServiceActivationPolicyApplyConfiguration]
}

// newServiceActivationPolicies returns a ServiceActivationPolicies
func newServiceActivationPolicies(c *NetworkingV1alpha3Client, namespace string) *serviceActivationPolicies {
	return &serviceActivationPolicies{
		gentype.NewClientWithListAndApply[*networkingv1alpha3.ServiceActivationPolicy, *networkingv1alpha3.ServiceActivationPolicyList, *applyconfigurationnetworkingv1alpha3.ServiceActivationPolicyApplyConfiguration](
			"serviceactivationpolicies",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *networkingv1alpha3.ServiceActivationPolicy {
				return &networkingv1alpha3.ServiceActivationPolicy{}
			},
			func() *networkingv1alpha3.ServiceActivationPolicyList {
				return &networkingv1alpha3.ServiceActivationPolicyList{}
			},
		),
	}
}
