//
// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha3

import (
	securityv1alpha3 "github.com/kdubbo/client-go/pkg/apis/security/v1alpha3"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// PeerAuthenticationLister helps list PeerAuthentications.
// All objects returned here must be treated as read-only.
type PeerAuthenticationLister interface {
	// List lists all PeerAuthentications in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*securityv1alpha3.PeerAuthentication, err error)
	// PeerAuthentications returns an object that can list and get PeerAuthentications.
	PeerAuthentications(namespace string) PeerAuthenticationNamespaceLister
	PeerAuthenticationListerExpansion
}

// peerAuthenticationLister implements the PeerAuthenticationLister interface.
type peerAuthenticationLister struct {
	listers.ResourceIndexer[*securityv1alpha3.PeerAuthentication]
}

// NewPeerAuthenticationLister returns a new PeerAuthenticationLister.
func NewPeerAuthenticationLister(indexer cache.Indexer) PeerAuthenticationLister {
	return &peerAuthenticationLister{listers.New[*securityv1alpha3.PeerAuthentication](indexer, securityv1alpha3.Resource("peerauthentication"))}
}

// PeerAuthentications returns an object that can list and get PeerAuthentications.
func (s *peerAuthenticationLister) PeerAuthentications(namespace string) PeerAuthenticationNamespaceLister {
	return peerAuthenticationNamespaceLister{listers.NewNamespaced[*securityv1alpha3.PeerAuthentication](s.ResourceIndexer, namespace)}
}

// PeerAuthenticationNamespaceLister helps list and get PeerAuthentications.
// All objects returned here must be treated as read-only.
type PeerAuthenticationNamespaceLister interface {
	// List lists all PeerAuthentications in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*securityv1alpha3.PeerAuthentication, err error)
	// Get retrieves the PeerAuthentication from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*securityv1alpha3.PeerAuthentication, error)
	PeerAuthenticationNamespaceListerExpansion
}

// peerAuthenticationNamespaceLister implements the PeerAuthenticationNamespaceLister
// interface.
type peerAuthenticationNamespaceLister struct {
	listers.ResourceIndexer[*securityv1alpha3.PeerAuthentication]
}
