//
// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha3

import (
	securityv1alpha3 "github.com/kdubbo/client-go/pkg/apis/security/v1alpha3"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// RequestAuthenticationLister helps list RequestAuthentications.
// All objects returned here must be treated as read-only.
type RequestAuthenticationLister interface {
	// List lists all RequestAuthentications in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*securityv1alpha3.RequestAuthentication, err error)
	// RequestAuthentications returns an object that can list and get RequestAuthentications.
	RequestAuthentications(namespace string) RequestAuthenticationNamespaceLister
	RequestAuthenticationListerExpansion
}

// requestAuthenticationLister implements the RequestAuthenticationLister interface.
type requestAuthenticationLister struct {
	listers.ResourceIndexer[*securityv1alpha3.RequestAuthentication]
}

// NewRequestAuthenticationLister returns a new RequestAuthenticationLister.
func NewRequestAuthenticationLister(indexer cache.Indexer) RequestAuthenticationLister {
	return &requestAuthenticationLister{listers.New[*securityv1alpha3.RequestAuthentication](indexer, securityv1alpha3.Resource("requestauthentication"))}
}

// RequestAuthentications returns an object that can list and get RequestAuthentications.
func (s *requestAuthenticationLister) RequestAuthentications(namespace string) RequestAuthenticationNamespaceLister {
	return requestAuthenticationNamespaceLister{listers.NewNamespaced[*securityv1alpha3.RequestAuthentication](s.ResourceIndexer, namespace)}
}

// RequestAuthenticationNamespaceLister helps list and get RequestAuthentications.
// All objects returned here must be treated as read-only.
type RequestAuthenticationNamespaceLister interface {
	// List lists all RequestAuthentications in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*securityv1alpha3.RequestAuthentication, err error)
	// Get retrieves the RequestAuthentication from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*securityv1alpha3.RequestAuthentication, error)
	RequestAuthenticationNamespaceListerExpansion
}

// requestAuthenticationNamespaceLister implements the RequestAuthenticationNamespaceLister
// interface.
type requestAuthenticationNamespaceLister struct {
	listers.ResourceIndexer[*securityv1alpha3.RequestAuthentication]
}
