//
// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha3

import (
	telemetryv1alpha3 "github.com/kdubbo/client-go/pkg/apis/telemetry/v1alpha3"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// TelemetryLister helps list Telemetries.
// All objects returned here must be treated as read-only.
type TelemetryLister interface {
	// List lists all Telemetries in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*telemetryv1alpha3.Telemetry, err error)
	// Telemetries returns an object that can list and get Telemetries.
	Telemetries(namespace string) TelemetryNamespaceLister
	TelemetryListerExpansion
}

// telemetryLister implements the TelemetryLister interface.
type telemetryLister struct {
	listers.ResourceIndexer[*telemetryv1alpha3.Telemetry]
}

// NewTelemetryLister returns a new TelemetryLister.
func NewTelemetryLister(indexer cache.Indexer) TelemetryLister {
	return &telemetryLister{listers.New[*telemetryv1alpha3.Telemetry](indexer, telemetryv1alpha3.Resource("telemetry"))}
}

// Telemetries returns an object that can list and get Telemetries.
func (s *telemetryLister) Telemetries(namespace string) TelemetryNamespaceLister {
	return telemetryNamespaceLister{listers.NewNamespaced[*telemetryv1alpha3.Telemetry](s.ResourceIndexer, namespace)}
}

// TelemetryNamespaceLister helps list and get Telemetries.
// All objects returned here must be treated as read-only.
type TelemetryNamespaceLister interface {
	// List lists all Telemetries in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*telemetryv1alpha3.Telemetry, err error)
	// Get retrieves the Telemetry from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*telemetryv1alpha3.Telemetry, error)
	TelemetryNamespaceListerExpansion
}

// telemetryNamespaceLister implements the TelemetryNamespaceLister
// interface.
type telemetryNamespaceLister struct {
	listers.ResourceIndexer[*telemetryv1alpha3.Telemetry]
}
