//
// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha3

import (
	context "context"

	securityv1alpha3 "github.com/kdubbo/client-go/pkg/apis/security/v1alpha3"
	applyconfigurationsecurityv1alpha3 "github.com/kdubbo/client-go/pkg/applyconfiguration/security/v1alpha3"
	scheme "github.com/kdubbo/client-go/pkg/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// PeerAuthenticationsGetter has a method to return a PeerAuthenticationInterface.
// A group's client should implement this interface.
type PeerAuthenticationsGetter interface {
	PeerAuthentications(namespace string) PeerAuthenticationInterface
}

// PeerAuthenticationInterface has methods to work with PeerAuthentication resources.
type PeerAuthenticationInterface interface {
	Create(ctx context.Context, peerAuthentication *securityv1alpha3.PeerAuthentication, opts v1.CreateOptions) (*securityv1alpha3.PeerAuthentication, error)
	Update(ctx context.Context, peerAuthentication *securityv1alpha3.PeerAuthentication, opts v1.UpdateOptions) (*securityv1alpha3.PeerAuthentication, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, peerAuthentication *securityv1alpha3.PeerAuthentication, opts v1.UpdateOptions) (*securityv1alpha3.PeerAuthentication, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*securityv1alpha3.PeerAuthentication, error)
	List(ctx context.Context, opts v1.ListOptions) (*securityv1alpha3.PeerAuthenticationList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *securityv1alpha3.PeerAuthentication, err error)
	Apply(ctx context.Context, peerAuthentication *applyconfigurationsecurityv1alpha3.PeerAuthenticationApplyConfiguration, opts v1.ApplyOptions) (result *securityv1alpha3.PeerAuthentication, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, peerAuthentication *applyconfigurationsecurityv1alpha3.PeerAuthenticationApplyConfiguration, opts v1.ApplyOptions) (result *securityv1alpha3.PeerAuthentication, err error)
	PeerAuthenticationExpansion
}

// peerAuthentications implements PeerAuthenticationInterface
type peerAuthentications struct {
	*gentype.ClientWithListAndApply[*securityv1alpha3.PeerAuthentication, *securityv1alpha3.PeerAuthenticationList, *applyconfigurationsecurityv1alpha3.PeerAuthenticationApplyConfiguration]
}

// newPeerAuthentications returns a PeerAuthentications
func newPeerAuthentications(c *SecurityV1alpha3Client, namespace string) *peerAuthentications {
	return &peerAuthentications{
		gentype.NewClientWithListAndApply[*securityv1alpha3.PeerAuthentication, *securityv1alpha3.PeerAuthenticationList, *applyconfigurationsecurityv1alpha3.PeerAuthenticationApplyConfiguration](
			"peerauthentications",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *securityv1alpha3.PeerAuthentication { return &securityv1alpha3.PeerAuthentication{} },
			func() *securityv1alpha3.PeerAuthenticationList { return &securityv1alpha3.PeerAuthenticationList{} },
		),
	}
}
