//
// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha3

import (
	context "context"

	telemetryv1alpha3 "github.com/kdubbo/client-go/pkg/apis/telemetry/v1alpha3"
	applyconfigurationtelemetryv1alpha3 "github.com/kdubbo/client-go/pkg/applyconfiguration/telemetry/v1alpha3"
	scheme "github.com/kdubbo/client-go/pkg/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// TelemetriesGetter has a method to return a TelemetryInterface.
// A group's client should implement this interface.
type TelemetriesGetter interface {
	Telemetries(namespace string) TelemetryInterface
}

// TelemetryInterface has methods to work with Telemetry resources.
type TelemetryInterface interface {
	Create(ctx context.Context, telemetry *telemetryv1alpha3.Telemetry, opts v1.CreateOptions) (*telemetryv1alpha3.Telemetry, error)
	Update(ctx context.Context, telemetry *telemetryv1alpha3.Telemetry, opts v1.UpdateOptions) (*telemetryv1alpha3.Telemetry, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, telemetry *telemetryv1alpha3.Telemetry, opts v1.UpdateOptions) (*telemetryv1alpha3.Telemetry, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*telemetryv1alpha3.Telemetry, error)
	List(ctx context.Context, opts v1.ListOptions) (*telemetryv1alpha3.TelemetryList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *telemetryv1alpha3.Telemetry, err error)
	Apply(ctx context.Context, telemetry *applyconfigurationtelemetryv1alpha3.TelemetryApplyConfiguration, opts v1.ApplyOptions) (result *telemetryv1alpha3.Telemetry, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, telemetry *applyconfigurationtelemetryv1alpha3.TelemetryApplyConfiguration, opts v1.ApplyOptions) (result *telemetryv1alpha3.Telemetry, err error)
	TelemetryExpansion
}

// telemetries implements TelemetryInterface
type telemetries struct {
	*gentype.ClientWithListAndApply[*telemetryv1alpha3.Telemetry, *telemetryv1alpha3.TelemetryList, *applyconfigurationtelemetryv1alpha3.TelemetryApplyConfiguration]
}

// newTelemetries returns a Telemetries
func newTelemetries(c *TelemetryV1alpha3Client, namespace string) *telemetries {
	return &telemetries{
		gentype.NewClientWithListAndApply[*telemetryv1alpha3.Telemetry, *telemetryv1alpha3.TelemetryList, *applyconfigurationtelemetryv1alpha3.TelemetryApplyConfiguration](
			"telemetries",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *telemetryv1alpha3.Telemetry { return &telemetryv1alpha3.Telemetry{} },
			func() *telemetryv1alpha3.TelemetryList { return &telemetryv1alpha3.TelemetryList{} },
		),
	}
}
