//
// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/kdubbo/client-go/pkg/apis/telemetry/v1alpha1"
	telemetryv1alpha1 "github.com/kdubbo/client-go/pkg/applyconfiguration/telemetry/v1alpha1"
	typedtelemetryv1alpha1 "github.com/kdubbo/client-go/pkg/clientset/versioned/typed/telemetry/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeTelemetries implements TelemetryInterface
type fakeTelemetries struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.Telemetry, *v1alpha1.TelemetryList, *telemetryv1alpha1.TelemetryApplyConfiguration]
	Fake *FakeTelemetryV1alpha1
}

func newFakeTelemetries(fake *FakeTelemetryV1alpha1, namespace string) typedtelemetryv1alpha1.TelemetryInterface {
	return &fakeTelemetries{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.Telemetry, *v1alpha1.TelemetryList, *telemetryv1alpha1.TelemetryApplyConfiguration](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("telemetries"),
			v1alpha1.SchemeGroupVersion.WithKind("Telemetry"),
			func() *v1alpha1.Telemetry { return &v1alpha1.Telemetry{} },
			func() *v1alpha1.TelemetryList { return &v1alpha1.TelemetryList{} },
			func(dst, src *v1alpha1.TelemetryList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.TelemetryList) []*v1alpha1.Telemetry { return list.Items },
			func(list *v1alpha1.TelemetryList, items []*v1alpha1.Telemetry) {
				list.Items = items
			},
		),
		fake,
	}
}
