//
// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package applyconfiguration

import (
	v1alpha3 "github.com/kdubbo/client-go/pkg/apis/networking/v1alpha3"
	securityv1alpha3 "github.com/kdubbo/client-go/pkg/apis/security/v1alpha3"
	internal "github.com/kdubbo/client-go/pkg/applyconfiguration/internal"
	networkingv1alpha3 "github.com/kdubbo/client-go/pkg/applyconfiguration/networking/v1alpha3"
	applyconfigurationsecurityv1alpha3 "github.com/kdubbo/client-go/pkg/applyconfiguration/security/v1alpha3"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
)

// ForKind returns an apply configuration type for the given GroupVersionKind, or nil if no
// apply configuration type exists for the given GroupVersionKind.
func ForKind(kind schema.GroupVersionKind) interface{} {
	switch kind {
	// Group=networking.dubbo.apache.org, Version=v1alpha3
	case v1alpha3.SchemeGroupVersion.WithKind("CircuitBreakerPolicy"):
		return &networkingv1alpha3.CircuitBreakerPolicyApplyConfiguration{}

		// Group=security.dubbo.apache.org, Version=v1alpha3
	case securityv1alpha3.SchemeGroupVersion.WithKind("AuthorizationPolicy"):
		return &applyconfigurationsecurityv1alpha3.AuthorizationPolicyApplyConfiguration{}
	case securityv1alpha3.SchemeGroupVersion.WithKind("PeerAuthentication"):
		return &applyconfigurationsecurityv1alpha3.PeerAuthenticationApplyConfiguration{}
	case securityv1alpha3.SchemeGroupVersion.WithKind("RequestAuthentication"):
		return &applyconfigurationsecurityv1alpha3.RequestAuthenticationApplyConfiguration{}

	}
	return nil
}

func NewTypeConverter(scheme *runtime.Scheme) managedfields.TypeConverter {
	return managedfields.NewSchemeTypeConverter(scheme, internal.Parser())
}
