//
// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha3

import (
	internalinterfaces "github.com/kdubbo/client-go/pkg/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// CircuitBreakerPolicies returns a CircuitBreakerPolicyInformer.
	CircuitBreakerPolicies() CircuitBreakerPolicyInformer
	// DxgateServices returns a DxgateServiceInformer.
	DxgateServices() DxgateServiceInformer
	// FaultInjectionPolicies returns a FaultInjectionPolicyInformer.
	FaultInjectionPolicies() FaultInjectionPolicyInformer
	// ServiceActivationPolicies returns a ServiceActivationPolicyInformer.
	ServiceActivationPolicies() ServiceActivationPolicyInformer
	// ServiceEntries returns a ServiceEntryInformer.
	ServiceEntries() ServiceEntryInformer
	// WorkloadEntries returns a WorkloadEntryInformer.
	WorkloadEntries() WorkloadEntryInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// CircuitBreakerPolicies returns a CircuitBreakerPolicyInformer.
func (v *version) CircuitBreakerPolicies() CircuitBreakerPolicyInformer {
	return &circuitBreakerPolicyInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// DxgateServices returns a DxgateServiceInformer.
func (v *version) DxgateServices() DxgateServiceInformer {
	return &dxgateServiceInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// FaultInjectionPolicies returns a FaultInjectionPolicyInformer.
func (v *version) FaultInjectionPolicies() FaultInjectionPolicyInformer {
	return &faultInjectionPolicyInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// ServiceActivationPolicies returns a ServiceActivationPolicyInformer.
func (v *version) ServiceActivationPolicies() ServiceActivationPolicyInformer {
	return &serviceActivationPolicyInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// ServiceEntries returns a ServiceEntryInformer.
func (v *version) ServiceEntries() ServiceEntryInformer {
	return &serviceEntryInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// WorkloadEntries returns a WorkloadEntryInformer.
func (v *version) WorkloadEntries() WorkloadEntryInformer {
	return &workloadEntryInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
