//
// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha3

import (
	networkingv1alpha3 "github.com/kdubbo/client-go/pkg/apis/networking/v1alpha3"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// CircuitBreakerPolicyLister helps list CircuitBreakerPolicies.
// All objects returned here must be treated as read-only.
type CircuitBreakerPolicyLister interface {
	// List lists all CircuitBreakerPolicies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*networkingv1alpha3.CircuitBreakerPolicy, err error)
	// CircuitBreakerPolicies returns an object that can list and get CircuitBreakerPolicies.
	CircuitBreakerPolicies(namespace string) CircuitBreakerPolicyNamespaceLister
	CircuitBreakerPolicyListerExpansion
}

// circuitBreakerPolicyLister implements the CircuitBreakerPolicyLister interface.
type circuitBreakerPolicyLister struct {
	listers.ResourceIndexer[*networkingv1alpha3.CircuitBreakerPolicy]
}

// NewCircuitBreakerPolicyLister returns a new CircuitBreakerPolicyLister.
func NewCircuitBreakerPolicyLister(indexer cache.Indexer) CircuitBreakerPolicyLister {
	return &circuitBreakerPolicyLister{listers.New[*networkingv1alpha3.CircuitBreakerPolicy](indexer, networkingv1alpha3.Resource("circuitbreakerpolicy"))}
}

// CircuitBreakerPolicies returns an object that can list and get CircuitBreakerPolicies.
func (s *circuitBreakerPolicyLister) CircuitBreakerPolicies(namespace string) CircuitBreakerPolicyNamespaceLister {
	return circuitBreakerPolicyNamespaceLister{listers.NewNamespaced[*networkingv1alpha3.CircuitBreakerPolicy](s.ResourceIndexer, namespace)}
}

// CircuitBreakerPolicyNamespaceLister helps list and get CircuitBreakerPolicies.
// All objects returned here must be treated as read-only.
type CircuitBreakerPolicyNamespaceLister interface {
	// List lists all CircuitBreakerPolicies in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*networkingv1alpha3.CircuitBreakerPolicy, err error)
	// Get retrieves the CircuitBreakerPolicy from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*networkingv1alpha3.CircuitBreakerPolicy, error)
	CircuitBreakerPolicyNamespaceListerExpansion
}

// circuitBreakerPolicyNamespaceLister implements the CircuitBreakerPolicyNamespaceLister
// interface.
type circuitBreakerPolicyNamespaceLister struct {
	listers.ResourceIndexer[*networkingv1alpha3.CircuitBreakerPolicy]
}
