//
// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha3

import (
	networkingv1alpha3 "github.com/kdubbo/client-go/pkg/apis/networking/v1alpha3"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// DxgateServiceLister helps list DxgateServices.
// All objects returned here must be treated as read-only.
type DxgateServiceLister interface {
	// List lists all DxgateServices in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*networkingv1alpha3.DxgateService, err error)
	// DxgateServices returns an object that can list and get DxgateServices.
	DxgateServices(namespace string) DxgateServiceNamespaceLister
	DxgateServiceListerExpansion
}

// dxgateServiceLister implements the DxgateServiceLister interface.
type dxgateServiceLister struct {
	listers.ResourceIndexer[*networkingv1alpha3.DxgateService]
}

// NewDxgateServiceLister returns a new DxgateServiceLister.
func NewDxgateServiceLister(indexer cache.Indexer) DxgateServiceLister {
	return &dxgateServiceLister{listers.New[*networkingv1alpha3.DxgateService](indexer, networkingv1alpha3.Resource("dxgateservice"))}
}

// DxgateServices returns an object that can list and get DxgateServices.
func (s *dxgateServiceLister) DxgateServices(namespace string) DxgateServiceNamespaceLister {
	return dxgateServiceNamespaceLister{listers.NewNamespaced[*networkingv1alpha3.DxgateService](s.ResourceIndexer, namespace)}
}

// DxgateServiceNamespaceLister helps list and get DxgateServices.
// All objects returned here must be treated as read-only.
type DxgateServiceNamespaceLister interface {
	// List lists all DxgateServices in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*networkingv1alpha3.DxgateService, err error)
	// Get retrieves the DxgateService from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*networkingv1alpha3.DxgateService, error)
	DxgateServiceNamespaceListerExpansion
}

// dxgateServiceNamespaceLister implements the DxgateServiceNamespaceLister
// interface.
type dxgateServiceNamespaceLister struct {
	listers.ResourceIndexer[*networkingv1alpha3.DxgateService]
}
