//
// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha3

// CircuitBreakerPolicyListerExpansion allows custom methods to be added to
// CircuitBreakerPolicyLister.
type CircuitBreakerPolicyListerExpansion interface{}

// CircuitBreakerPolicyNamespaceListerExpansion allows custom methods to be added to
// CircuitBreakerPolicyNamespaceLister.
type CircuitBreakerPolicyNamespaceListerExpansion interface{}

// ServiceEntryListerExpansion allows custom methods to be added to
// ServiceEntryLister.
type ServiceEntryListerExpansion interface{}

// ServiceEntryNamespaceListerExpansion allows custom methods to be added to
// ServiceEntryNamespaceLister.
type ServiceEntryNamespaceListerExpansion interface{}

// WorkloadEntryListerExpansion allows custom methods to be added to
// WorkloadEntryLister.
type WorkloadEntryListerExpansion interface{}

// WorkloadEntryNamespaceListerExpansion allows custom methods to be added to
// WorkloadEntryNamespaceLister.
type WorkloadEntryNamespaceListerExpansion interface{}
