//
// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha3

import (
	networkingv1alpha3 "github.com/kdubbo/client-go/pkg/apis/networking/v1alpha3"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// FaultInjectionPolicyLister helps list FaultInjectionPolicies.
// All objects returned here must be treated as read-only.
type FaultInjectionPolicyLister interface {
	// List lists all FaultInjectionPolicies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*networkingv1alpha3.FaultInjectionPolicy, err error)
	// FaultInjectionPolicies returns an object that can list and get FaultInjectionPolicies.
	FaultInjectionPolicies(namespace string) FaultInjectionPolicyNamespaceLister
	FaultInjectionPolicyListerExpansion
}

// faultInjectionPolicyLister implements the FaultInjectionPolicyLister interface.
type faultInjectionPolicyLister struct {
	listers.ResourceIndexer[*networkingv1alpha3.FaultInjectionPolicy]
}

// NewFaultInjectionPolicyLister returns a new FaultInjectionPolicyLister.
func NewFaultInjectionPolicyLister(indexer cache.Indexer) FaultInjectionPolicyLister {
	return &faultInjectionPolicyLister{listers.New[*networkingv1alpha3.FaultInjectionPolicy](indexer, networkingv1alpha3.Resource("faultinjectionpolicy"))}
}

// FaultInjectionPolicies returns an object that can list and get FaultInjectionPolicies.
func (s *faultInjectionPolicyLister) FaultInjectionPolicies(namespace string) FaultInjectionPolicyNamespaceLister {
	return faultInjectionPolicyNamespaceLister{listers.NewNamespaced[*networkingv1alpha3.FaultInjectionPolicy](s.ResourceIndexer, namespace)}
}

// FaultInjectionPolicyNamespaceLister helps list and get FaultInjectionPolicies.
// All objects returned here must be treated as read-only.
type FaultInjectionPolicyNamespaceLister interface {
	// List lists all FaultInjectionPolicies in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*networkingv1alpha3.FaultInjectionPolicy, err error)
	// Get retrieves the FaultInjectionPolicy from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*networkingv1alpha3.FaultInjectionPolicy, error)
	FaultInjectionPolicyNamespaceListerExpansion
}

// faultInjectionPolicyNamespaceLister implements the FaultInjectionPolicyNamespaceLister
// interface.
type faultInjectionPolicyNamespaceLister struct {
	listers.ResourceIndexer[*networkingv1alpha3.FaultInjectionPolicy]
}
