//
// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha3

import (
	networkingv1alpha3 "github.com/kdubbo/client-go/pkg/apis/networking/v1alpha3"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ServiceActivationPolicyLister helps list ServiceActivationPolicies.
// All objects returned here must be treated as read-only.
type ServiceActivationPolicyLister interface {
	// List lists all ServiceActivationPolicies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*networkingv1alpha3.ServiceActivationPolicy, err error)
	// ServiceActivationPolicies returns an object that can list and get ServiceActivationPolicies.
	ServiceActivationPolicies(namespace string) ServiceActivationPolicyNamespaceLister
	ServiceActivationPolicyListerExpansion
}

// serviceActivationPolicyLister implements the ServiceActivationPolicyLister interface.
type serviceActivationPolicyLister struct {
	listers.ResourceIndexer[*networkingv1alpha3.ServiceActivationPolicy]
}

// NewServiceActivationPolicyLister returns a new ServiceActivationPolicyLister.
func NewServiceActivationPolicyLister(indexer cache.Indexer) ServiceActivationPolicyLister {
	return &serviceActivationPolicyLister{listers.New[*networkingv1alpha3.ServiceActivationPolicy](indexer, networkingv1alpha3.Resource("serviceactivationpolicy"))}
}

// ServiceActivationPolicies returns an object that can list and get ServiceActivationPolicies.
func (s *serviceActivationPolicyLister) ServiceActivationPolicies(namespace string) ServiceActivationPolicyNamespaceLister {
	return serviceActivationPolicyNamespaceLister{listers.NewNamespaced[*networkingv1alpha3.ServiceActivationPolicy](s.ResourceIndexer, namespace)}
}

// ServiceActivationPolicyNamespaceLister helps list and get ServiceActivationPolicies.
// All objects returned here must be treated as read-only.
type ServiceActivationPolicyNamespaceLister interface {
	// List lists all ServiceActivationPolicies in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*networkingv1alpha3.ServiceActivationPolicy, err error)
	// Get retrieves the ServiceActivationPolicy from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*networkingv1alpha3.ServiceActivationPolicy, error)
	ServiceActivationPolicyNamespaceListerExpansion
}

// serviceActivationPolicyNamespaceLister implements the ServiceActivationPolicyNamespaceLister
// interface.
type serviceActivationPolicyNamespaceLister struct {
	listers.ResourceIndexer[*networkingv1alpha3.ServiceActivationPolicy]
}
